### ISSUE TITLE
Decide what to do with MySql warnings

### ISSUE THREAD

**Issue by chilts** [mozilla/fxa-auth-db-server#102]
As per much of the discussion here https://github.com/mozilla/fxa-auth-db-server/pull/95 we decided to split off our plan (or current lack of it) for MySql warnings. That PR only handles sqlexception events but not sqlwarning events.

Currently we don't catch any of these (pre-Stored Procedures) so we decided to keep that the same, but we should figure out what to do with them. We really shouldn't trigger any of these, but that doesn't mean we won't.

**Comment by rfk** [comment]
Closing this out, we're not going to prioritize it
