### ISSUE TITLE
fresh install fails to create DB

### ISSUE THREAD

**Issue by Stopi** [mozilla/fxa-auth-db-server#105]
Hi guys,

following the README, I wasn't able to get any DB.
Here's how to reproduce :

``` bash
  git clone https://github.com/mozilla/fxa-auth-db-server.git
  cd fxa-auth-db-server
  vi .fxa_dbrc
  npm install
  node bin/db_patcher.js
```

This last command just do **nothing**, no database created, no output, no log.

My `.fxa_dbrc` contains :

```
{
  "master": {
    "user": "mozilla",
    "password": "secret"
  },
  "slave": {
    "user": "mozilla",
    "password": "secret"
  }
}
```

Credential are verified, I can connect to mysql using command line :

``` bash
mysql -u mozilla -psecret
```

Then I'm able to create a database named fxa (all privileges granted).
I've also checked other default config values : port 3306, hostname localhost, etc.

I'm using node.js **0.10.21** and mysql **5.5.40**.
It seems I've fullfiled all requirements, am I wrong ?

**Comment by chilts** [comment]
Fixed error reporting is now in `mysql-patcher` and released as v0.5.0 - https://www.npmjs.com/package/mysql-patcher - next step is to update this repo to use it.
