### ISSUE TITLE
Implement .fxa_dbrc support

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-db-server#107]
The README says you can use a `.fxa_dbrc` file to set local config params, but AFAICT this is not actually implemented.  We should either implement it, or remove it from the docs.

**Comment by chilts** [comment]
We should remove it from the docs since that was from when we were using `rc`. Since we switched to convict, this no longer works. Convict switch here -> https://github.com/mozilla/fxa-auth-db-server/pull/55
