### ISSUE TITLE
Document minimum required version of MySQL

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-db-server#110]
As seen in #109, older mysql versions do not support all the fancy stored-procedure-error-handler stuff that we're using here.  We should determine the minimum version of MySQL that supports these features and document it for third-party installs.

**Comment by rfk** [comment]
Per discussion with @jrgm, let's not commit to a minimum supported version as we don't want to tie our hands.  Rather, we should document which version we're using in production and people can debug backwards from there.

**Comment by chilts** [comment]
From here: http://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_MySQL.html#MySQL.Concepts.VersionMgmt

"Amazon RDS currently supports MySQL versions 5.6, 5.5, and 5.1."

@jrgm: what is the version we're currently using? Let's just document that as "this is what works for us, for other versions ymmv". :)

**Comment by jrgm** [comment]
@chilts: we use MySQL 5.6.19a in stage (5.6.21 is the other option in the 5.6 choices on Amazon RDS).
@ckolos: actually, can you confirm that we use 5.6.19a in production (if not, I'll upgrade to 5.6.21 in stage).

**Comment by ckolos** [comment]
Server version: 5.6.21-log MySQL Community Server (GPL)
