### ISSUE TITLE
Problem with current patch solution

### ISSUE THREAD

**Issue by chilts** [mozilla/fxa-auth-db-server#114]
Currently we run into problems when we release to production if we have more than one database patch.

If a release has only one patch, then both dev and prod are patched correctly and there is no problem.

The problem with two (or more) patches goes like this:

1. when the DB server starts up, it checks that the DB patch level is either `n` or `n+1` (ie. the current patch or the one after). This allows DB patching to occur prior to the release to make things easier. If the patch level is not `(n, n+1)` then the DB refuses to start.
2. in the case where we have two patches, we can't patch the database up front with both patches since that could cause problems for the current stack if one of the DB servers needs to restart. It would fail due to the current db patch level being `n+2`.

One solution would be to merge the patches into a single patch, but this doesn't work if dev has already been patched with the first one.

Some general solutions to this could be:

1. do not fail if the database patch level is not what we expect and instead just log it (loudly). This relies on other current procedures to make sure only particular stacks run against the current database (patched or not).
2. (or) instead of failing if the patch level isn't `n` or `n+1`, only fail if the patch level is `<n`. That way if we patch the database twice or more in a release, then the current stack would be okay if any DB server needed to restart.

A temporary solution to the current problem (for train 29):

1. change the behaviour of the DB server so that a patch level mis-match is only logged
2. patch the prod database with both patches but only increment the patch level by one.
3. release the new stack. Both stacks. should be happy since they the former is fulfilled and the latter is just logged.
4. once the new stack is proven and the old stack goes away, update the patch level in the database

Currently my thinking for the overall problem is to check for `<n` and fail on that, rather than fail on anything other than `n` or `n+1`.

Any other thoughts?

**Comment by chilts** [comment]
@jrgm: Does the temporary solution for train-29 work for you?

**Comment by rfk** [comment]
> Currently my thinking for the overall problem is to check for <n and fail on that,
> rather than fail on anything other than n or n+1.

This sounds like the best compromise solution to me as well.

**Comment by chilts** [comment]
Fixed in this PR here : https://github.com/mozilla/fxa-auth-db-server/pull/121

**Comment by rfk** [comment]
Needs merge into reverse backends branch?

**Comment by chilts** [comment]
Added this commit on the reverse-with-tests branch : https://github.com/chilts/fxa-auth-db-mysql/commit/dbc10c9fbd76f98fe8190d59a90d5b171f1fa2ac

This does the '<n' check, and not just log what the status is.

**Comment by chilts** [comment]
Scrap that, my formatting was lousy : https://github.com/chilts/fxa-auth-db-mysql/commit/f74f8c99406a204d35c304edb912c8bf6acf8e54
