### ISSUE TITLE
package.json->"main" refers to non-existent "index.js"

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-auth-db-server#115]
## STR
1. check out the master branch
1. open `package.json`
1. the file from the [following line](https://github.com/mozilla/fxa-auth-db-server/blob/68a44436e4358008020da7eaac0d9f5ae60f3709/package.json#L5) does not exist:
```json
 "main": "index.js",
```

This causes a problem when trying to include the branch into fxa-auth-db-mem.

**Comment by chilts** [comment]
This has now been fixed as part of the `reverse` branch being merged.
