### ISSUE TITLE
Fill in README for the DB API for the reverse server

### ISSUE THREAD

**Issue by chilts** [mozilla/fxa-auth-db-server#119]
As mentioned here : https://github.com/mozilla/fxa-auth-db-server/pull/116#discussion_r23665432

**Comment by chilts** [comment]
There is currently a WIP branch here:

* https://github.com/chilts/fxa-auth-db-server/blob/server-api-docs/docs/Server_API.md

I'll be going through it again with a finer toothcomb. Any thoughts welcome as it's still ongoing (yes, some words are still missing but the operations are captured).

**Comment by rfk** [comment]
I'm going to be a little cheeky and target this for train-39, since it looks like you've mostly got it under control and we just need to get it over the line

**Comment by chilts** [comment]
Done here : https://github.com/mozilla/fxa-auth-db-server/pull/145
