### ISSUE TITLE
How should we do different backends?

### ISSUE THREAD

**Issue by dannycoates** [mozilla/fxa-auth-db-server#60]
I've got this branch https://github.com/dannycoates/fxa-auth-db-server/tree/reverse and https://github.com/dannycoates/fxa-auth-db-mem

Is that how we want to do it? If lets refactor this mysql backend to it. If not lets discuss.

**Comment by chilts** [comment]
Same branches as above.

Now updated with MySql patches 5, 6 and 7 - deleting other tokens per user when adding a new one. Also fixes made for the memory backend which didn't do this properly either).

Still making sure everything is there though it is looking pretty much complete.

**Comment by chilts** [comment]
PR (and related) -> https://github.com/mozilla/fxa-auth-db-server/pull/116

**Comment by chilts** [comment]
A branch in progress for fxa-dev : https://github.com/mozilla/fxa-dev/tree/rfk/reverse-backends

**Comment by rfk** [comment]
:dancer: :dancer: :dancer:

This is, in theory, completely done and merged!

**Comment by chilts** [comment]
![superman-hugs-batman](https://cloud.githubusercontent.com/assets/3048/6049417/0e2ea55a-ad1c-11e4-9c4c-956258f06950.gif)
