### ISSUE TITLE
Stop passing a timestamp to the token pruning stored procedure

### ISSUE THREAD

**Issue by fmarier** [mozilla/fxa-auth-db-server#82]
In order to take power away from the auth-db-server, we could remove both timestamp parameters from the `prune` stored procedure. Instead, the stored procedure should get the time from MySQL and expire the tokens based on a fixed expiry time.

This will ensure that the auth-db-server cannot decide to expire all tokens at once.

(part of https://bugzilla.mozilla.org/show_bug.cgi?id=1045264)

**Comment by vladikoff** [comment]
@rfk we did some expiry work, what should this be part of?

**Comment by rfk** [comment]
I made a related feature card for discussion in product planning meeting:

  https://mozilla.aha.io/features/FXA-58

**Comment by rfk** [comment]
This is now in aha, closing out here
