### ISSUE TITLE
Add new database user with restricted permissions

### ISSUE THREAD

**Issue by chilts** [mozilla/fxa-auth-db-server#86]
Now that we have stored procedures for the database user to use - https://github.com/mozilla/fxa-auth-db-server/issues/81 - we need to add a new user which has ONLY those permissions to use them. (ie. no general SQL statements.)

**Comment by rfk** [comment]
We're going to revisit this with a different approach, closing out the bug

**Comment by chilts** [comment]
Randomly, I came across this one yesterday! :) /me :wave:

**Comment by rfk** [comment]
@chilts 👋 😁
